"""
Nobel Center — BIP.ContractID (local only, do not commit).

Generated from Baserow delentreprenader table 1182.
Regenerate: python3 scripts/generate_nobel_contract_id_from_baserow.py
"""

from __future__ import annotations

from typing import Any

# Baserow snapshot — metadata for validation / lookup (not published in git).
DELENTREPRENADER: dict[str, dict[str, Any]] = {
    'DE100': {
        'delentreprenad': 'DE100 -',
        'namn': '',
        'nummer': '100',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': False,
        'baserow_row_id': 1,
    },
    'DE101': {
        'delentreprenad': 'DE101 - Ledningsomläggning',
        'namn': 'Ledningsomläggning',
        'nummer': '101',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': False,
        'baserow_row_id': 2,
    },
    'DE102': {
        'delentreprenad': 'DE102 - Tungrivning',
        'namn': 'Tungrivning',
        'nummer': '102',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': False,
        'baserow_row_id': 3,
    },
    'DE103': {
        'delentreprenad': 'DE103 - Lättrivning',
        'namn': 'Lättrivning',
        'nummer': '103',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': False,
        'baserow_row_id': 4,
    },
    'DE104': {
        'delentreprenad': 'DE104 - Förstärkningssmide',
        'namn': 'Förstärkningssmide',
        'nummer': '104',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 5,
    },
    'DE105': {
        'delentreprenad': 'DE105 - Schaktning',
        'namn': 'Schaktning',
        'nummer': '105',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': False,
        'baserow_row_id': 6,
    },
    'DE106': {
        'delentreprenad': 'DE106 - Pålning',
        'namn': 'Pålning',
        'nummer': '106',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 7,
    },
    'DE107': {
        'delentreprenad': 'DE107 - Energibrunnsborrning',
        'namn': 'Energibrunnsborrning',
        'nummer': '107',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 8,
    },
    'DE108': {
        'delentreprenad': 'DE108 - Grundläggning/Mark',
        'namn': 'Grundläggning/Mark',
        'nummer': '108',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 9,
    },
    'DE109': {
        'delentreprenad': 'DE109 - Betong',
        'namn': 'Betong',
        'nummer': '109',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 10,
    },
    'DE110': {
        'delentreprenad': 'DE110 - Tätskikt under mark',
        'namn': 'Tätskikt under mark',
        'nummer': '110',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 11,
    },
    'DE111': {
        'delentreprenad': 'DE111 - Prefabstomme',
        'namn': 'Prefabstomme',
        'nummer': '111',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 12,
    },
    'DE112': {
        'delentreprenad': 'DE112 - Stålstomme',
        'namn': 'Stålstomme',
        'nummer': '112',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 13,
    },
    'DE113': {
        'delentreprenad': 'DE113 - Trästomme',
        'namn': 'Trästomme',
        'nummer': '113',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 14,
    },
    'DE114': {
        'delentreprenad': 'DE114 - Elementfasad',
        'namn': 'Elementfasad',
        'nummer': '114',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 15,
    },
    'DE115': {
        'delentreprenad': 'DE115 - Glaspartier (metall)',
        'namn': 'Glaspartier (metall)',
        'nummer': '115',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 16,
    },
    'DE116': {
        'delentreprenad': 'DE116 - Entrékarusell',
        'namn': 'Entrékarusell',
        'nummer': '116',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 17,
    },
    'DE117': {
        'delentreprenad': 'DE117 - Fönster',
        'namn': 'Fönster',
        'nummer': '117',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 19,
    },
    'DE118': {
        'delentreprenad': 'DE118 - Fönsterrenovering',
        'namn': 'Fönsterrenovering',
        'nummer': '118',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 18,
    },
    'DE119': {
        'delentreprenad': 'DE119 - Utfackningsväggar',
        'namn': 'Utfackningsväggar',
        'nummer': '119',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 20,
    },
    'DE120': {
        'delentreprenad': 'DE120 - Murning',
        'namn': 'Murning',
        'nummer': '120',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 21,
    },
    'DE121': {
        'delentreprenad': 'DE121 - Putsning',
        'namn': 'Putsning',
        'nummer': '121',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 22,
    },
    'DE122': {
        'delentreprenad': 'DE122 - Fasadbeklädnad',
        'namn': 'Fasadbeklädnad',
        'nummer': '122',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 23,
    },
    'DE123': {
        'delentreprenad': 'DE123 - Takarbeten',
        'namn': 'Takarbeten',
        'nummer': '123',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 24,
    },
    'DE124': {
        'delentreprenad': 'DE124 - Plåt',
        'namn': 'Plåt',
        'nummer': '124',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 25,
    },
    'DE125': {
        'delentreprenad': 'DE125 - Ståltrappor',
        'namn': 'Ståltrappor',
        'nummer': '125',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 26,
    },
    'DE126': {
        'delentreprenad': 'DE126 - Trätrappor',
        'namn': 'Trätrappor',
        'nummer': '126',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 27,
    },
    'DE127': {
        'delentreprenad': 'DE127 - Finplanering',
        'namn': 'Finplanering',
        'nummer': '127',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': True,
        'baserow_row_id': 28,
    },
    'DE128': {
        'delentreprenad': 'DE128 - Stensockel',
        'namn': 'Stensockel',
        'nummer': '128',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': False,
        'baserow_row_id': 29,
    },
    'DE129': {
        'delentreprenad': 'DE129 - Vakant',
        'namn': 'Vakant',
        'nummer': '129',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': False,
        'baserow_row_id': 30,
    },
    'DE130': {
        'delentreprenad': 'DE130 - Vakant',
        'namn': 'Vakant',
        'nummer': '130',
        'huvudgrupp': '1. STORA BYGGENTREPRENADER',
        'huvudgrupp_id': 3841,
        'grupp': '1',
        'modelleras_3d': False,
        'baserow_row_id': 31,
    },
    'DE200': {
        'delentreprenad': 'DE200 -',
        'namn': '',
        'nummer': '200',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': False,
        'baserow_row_id': 32,
    },
    'DE201': {
        'delentreprenad': 'DE201 - Hiss',
        'namn': 'Hiss',
        'nummer': '201',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 33,
    },
    'DE202': {
        'delentreprenad': 'DE202 - Varuhiss',
        'namn': 'Varuhiss',
        'nummer': '202',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 34,
    },
    'DE203': {
        'delentreprenad': 'DE203 - Lyftbord',
        'namn': 'Lyftbord',
        'nummer': '203',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 35,
    },
    'DE204': {
        'delentreprenad': 'DE204 - Rulltrappor',
        'namn': 'Rulltrappor',
        'nummer': '204',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 36,
    },
    'DE205': {
        'delentreprenad': 'DE205 - Portar',
        'namn': 'Portar',
        'nummer': '205',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 37,
    },
    'DE206': {
        'delentreprenad': 'DE206 - Jalusier',
        'namn': 'Jalusier',
        'nummer': '206',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 38,
    },
    'DE207': {
        'delentreprenad': 'DE207 - Sprinkler',
        'namn': 'Sprinkler',
        'nummer': '207',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 39,
    },
    'DE208': {
        'delentreprenad': 'DE208 - Luftbehandling',
        'namn': 'Luftbehandling',
        'nummer': '208',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 40,
    },
    'DE209': {
        'delentreprenad': 'DE209 - Rör',
        'namn': 'Rör',
        'nummer': '209',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 41,
    },
    'DE210': {
        'delentreprenad': 'DE210 - El',
        'namn': 'El',
        'nummer': '210',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 42,
    },
    'DE211': {
        'delentreprenad': 'DE211 - SRÖ',
        'namn': 'SRÖ',
        'nummer': '211',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 43,
    },
    'DE212': {
        'delentreprenad': 'DE212 - Solavskärmning',
        'namn': 'Solavskärmning',
        'nummer': '212',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 44,
    },
    'DE213': {
        'delentreprenad': 'DE213 - Solceller',
        'namn': 'Solceller',
        'nummer': '213',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 45,
    },
    'DE214': {
        'delentreprenad': 'DE214 - Passagesystem',
        'namn': 'Passagesystem',
        'nummer': '214',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 46,
    },
    'DE215': {
        'delentreprenad': 'DE215 - Fjärrvärme/Fjärrkyla',
        'namn': 'Fjärrvärme/Fjärrkyla',
        'nummer': '215',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 47,
    },
    'DE216': {
        'delentreprenad': 'DE216 - Anslutning Kraft',
        'namn': 'Anslutning Kraft',
        'nummer': '216',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 48,
    },
    'DE217': {
        'delentreprenad': 'DE217 - Fiber',
        'namn': 'Fiber',
        'nummer': '217',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 49,
    },
    'DE218': {
        'delentreprenad': 'DE218 - Fastighetsnätverk',
        'namn': 'Fastighetsnätverk',
        'nummer': '218',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 50,
    },
    'DE219': {
        'delentreprenad': 'DE219 - Mobilförstärkning',
        'namn': 'Mobilförstärkning',
        'nummer': '219',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 51,
    },
    'DE220': {
        'delentreprenad': 'DE220 - Luftbehandlingsaggregat (leverans)',
        'namn': 'Luftbehandlingsaggregat (leverans)',
        'nummer': '220',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': False,
        'baserow_row_id': 52,
    },
    'DE221': {
        'delentreprenad': 'DE221 - Kylmaskiner (leverans)',
        'namn': 'Kylmaskiner (leverans)',
        'nummer': '221',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': False,
        'baserow_row_id': 53,
    },
    'DE222': {
        'delentreprenad': 'DE222 - AV Utrustning',
        'namn': 'AV Utrustning',
        'nummer': '222',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 54,
    },
    'DE223': {
        'delentreprenad': 'DE223 - Kökskyla',
        'namn': 'Kökskyla',
        'nummer': '223',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 55,
    },
    'DE224': {
        'delentreprenad': 'DE224 - Relining',
        'namn': 'Relining',
        'nummer': '224',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': False,
        'baserow_row_id': 56,
    },
    'DE225': {
        'delentreprenad': 'DE225 - Renvatten',
        'namn': 'Renvatten',
        'nummer': '225',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 57,
    },
    'DE226': {
        'delentreprenad': 'DE226 - Tryckluft',
        'namn': 'Tryckluft',
        'nummer': '226',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 58,
    },
    'DE227': {
        'delentreprenad': 'DE227 - Vakuum',
        'namn': 'Vakuum',
        'nummer': '227',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 59,
    },
    'DE228': {
        'delentreprenad': 'DE228 - Gas',
        'namn': 'Gas',
        'nummer': '228',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 60,
    },
    'DE229': {
        'delentreprenad': 'DE229 - Batterirum',
        'namn': 'Batterirum',
        'nummer': '229',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 61,
    },
    'DE230': {
        'delentreprenad': 'DE230 - Reservkraft',
        'namn': 'Reservkraft',
        'nummer': '230',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': True,
        'baserow_row_id': 62,
    },
    'DE231': {
        'delentreprenad': 'DE231 - Vakant',
        'namn': 'Vakant',
        'nummer': '231',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': False,
        'baserow_row_id': 63,
    },
    'DE232': {
        'delentreprenad': 'DE232 - Vakant',
        'namn': 'Vakant',
        'nummer': '232',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': False,
        'baserow_row_id': 64,
    },
    'DE233': {
        'delentreprenad': 'DE233 - Vakant',
        'namn': 'Vakant',
        'nummer': '233',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': False,
        'baserow_row_id': 65,
    },
    'DE234': {
        'delentreprenad': 'DE234 - Vakant',
        'namn': 'Vakant',
        'nummer': '234',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': False,
        'baserow_row_id': 66,
    },
    'DE235': {
        'delentreprenad': 'DE235 - Vakant',
        'namn': 'Vakant',
        'nummer': '235',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': False,
        'baserow_row_id': 67,
    },
    'DE236': {
        'delentreprenad': 'DE236 - Vakant',
        'namn': 'Vakant',
        'nummer': '236',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': False,
        'baserow_row_id': 68,
    },
    'DE237': {
        'delentreprenad': 'DE237 - Vakant',
        'namn': 'Vakant',
        'nummer': '237',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': False,
        'baserow_row_id': 69,
    },
    'DE238': {
        'delentreprenad': 'DE238 - Vakant',
        'namn': 'Vakant',
        'nummer': '238',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': False,
        'baserow_row_id': 70,
    },
    'DE239': {
        'delentreprenad': 'DE239 - Vakant',
        'namn': 'Vakant',
        'nummer': '239',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': False,
        'baserow_row_id': 71,
    },
    'DE240': {
        'delentreprenad': 'DE240 - Vakant',
        'namn': 'Vakant',
        'nummer': '240',
        'huvudgrupp': '2. INSTALLATIONSENTREPRENADER',
        'huvudgrupp_id': 3843,
        'grupp': '2',
        'modelleras_3d': False,
        'baserow_row_id': 72,
    },
    'DE300': {
        'delentreprenad': 'DE300 -',
        'namn': '',
        'nummer': '300',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': False,
        'baserow_row_id': 73,
    },
    'DE301': {
        'delentreprenad': 'DE301 - Håltagning',
        'namn': 'Håltagning',
        'nummer': '301',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': True,
        'baserow_row_id': 74,
    },
    'DE302': {
        'delentreprenad': 'DE302 - Upphängningar',
        'namn': 'Upphängningar',
        'nummer': '302',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': True,
        'baserow_row_id': 75,
    },
    'DE303': {
        'delentreprenad': 'DE303 - Brand & Ljudtätningar',
        'namn': 'Brand & Ljudtätningar',
        'nummer': '303',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': True,
        'baserow_row_id': 76,
    },
    'DE304': {
        'delentreprenad': 'DE304 - Lapp och lag',
        'namn': 'Lapp och lag',
        'nummer': '304',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': False,
        'baserow_row_id': 77,
    },
    'DE305': {
        'delentreprenad': 'DE305 - Golvavjämning',
        'namn': 'Golvavjämning',
        'nummer': '305',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': True,
        'baserow_row_id': 78,
    },
    'DE306': {
        'delentreprenad': 'DE306 - Mellanväggar',
        'namn': 'Mellanväggar',
        'nummer': '306',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': True,
        'baserow_row_id': 79,
    },
    'DE307': {
        'delentreprenad': 'DE307 - Glaspartier och systemväggar',
        'namn': 'Glaspartier och systemväggar',
        'nummer': '307',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': True,
        'baserow_row_id': 80,
    },
    'DE308': {
        'delentreprenad': 'DE308 - Glaspartier labb',
        'namn': 'Glaspartier labb',
        'nummer': '308',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': True,
        'baserow_row_id': 81,
    },
    'DE309': {
        'delentreprenad': 'DE309 - Bygg',
        'namn': 'Bygg',
        'nummer': '309',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': True,
        'baserow_row_id': 82,
    },
    'DE310': {
        'delentreprenad': 'DE310 - Finsnickeri',
        'namn': 'Finsnickeri',
        'nummer': '310',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': True,
        'baserow_row_id': 83,
    },
    'DE311': {
        'delentreprenad': 'DE311 - Finsmide',
        'namn': 'Finsmide',
        'nummer': '311',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': True,
        'baserow_row_id': 84,
    },
    'DE312': {
        'delentreprenad': 'DE312 - Fog',
        'namn': 'Fog',
        'nummer': '312',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': False,
        'baserow_row_id': 85,
    },
    'DE313': {
        'delentreprenad': 'DE313 - Leverans tillhandahållet material',
        'namn': 'Leverans tillhandahållet material',
        'nummer': '313',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': True,
        'baserow_row_id': 86,
    },
    'DE314': {
        'delentreprenad': 'DE314 - Vikvägg',
        'namn': 'Vikvägg',
        'nummer': '314',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': False,
        'baserow_row_id': 87,
    },
    'DE315': {
        'delentreprenad': 'DE315 - Återbruk innerdörrar',
        'namn': 'Återbruk innerdörrar',
        'nummer': '315',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': False,
        'baserow_row_id': 88,
    },
    'DE316': {
        'delentreprenad': 'DE316 - Vakant',
        'namn': 'Vakant',
        'nummer': '316',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': False,
        'baserow_row_id': 89,
    },
    'DE317': {
        'delentreprenad': 'DE317 - Vakant',
        'namn': 'Vakant',
        'nummer': '317',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': False,
        'baserow_row_id': 90,
    },
    'DE318': {
        'delentreprenad': 'DE318 - Vakant',
        'namn': 'Vakant',
        'nummer': '318',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': False,
        'baserow_row_id': 91,
    },
    'DE319': {
        'delentreprenad': 'DE319 - Vakant',
        'namn': 'Vakant',
        'nummer': '319',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': False,
        'baserow_row_id': 92,
    },
    'DE320': {
        'delentreprenad': 'DE320 - Vakant',
        'namn': 'Vakant',
        'nummer': '320',
        'huvudgrupp': '3. MINDRE BYGGENTREPRENADER',
        'huvudgrupp_id': 3842,
        'grupp': '3',
        'modelleras_3d': False,
        'baserow_row_id': 93,
    },
    'DE400': {
        'delentreprenad': 'DE400 -',
        'namn': '',
        'nummer': '400',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': False,
        'baserow_row_id': 94,
    },
    'DE401': {
        'delentreprenad': 'DE401 - Natursten',
        'namn': 'Natursten',
        'nummer': '401',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': True,
        'baserow_row_id': 95,
    },
    'DE402': {
        'delentreprenad': 'DE402 - Plattsättning',
        'namn': 'Plattsättning',
        'nummer': '402',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': True,
        'baserow_row_id': 96,
    },
    'DE403': {
        'delentreprenad': 'DE403 - Golvbeläggning',
        'namn': 'Golvbeläggning',
        'nummer': '403',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': True,
        'baserow_row_id': 97,
    },
    'DE404': {
        'delentreprenad': 'DE404 - Massagolv',
        'namn': 'Massagolv',
        'nummer': '404',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': True,
        'baserow_row_id': 98,
    },
    'DE405': {
        'delentreprenad': 'DE405 - Terrazzo',
        'namn': 'Terrazzo',
        'nummer': '405',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': True,
        'baserow_row_id': 99,
    },
    'DE406': {
        'delentreprenad': 'DE406 - Slipning golv',
        'namn': 'Slipning golv',
        'nummer': '406',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': False,
        'baserow_row_id': 100,
    },
    'DE407': {
        'delentreprenad': 'DE407 - Målning',
        'namn': 'Målning',
        'nummer': '407',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': True,
        'baserow_row_id': 101,
    },
    'DE408': {
        'delentreprenad': 'DE408 - Undertak',
        'namn': 'Undertak',
        'nummer': '408',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': True,
        'baserow_row_id': 102,
    },
    'DE409': {
        'delentreprenad': 'DE409 - Vakant',
        'namn': 'Vakant',
        'nummer': '409',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': False,
        'baserow_row_id': 103,
    },
    'DE410': {
        'delentreprenad': 'DE410 - Vakant',
        'namn': 'Vakant',
        'nummer': '410',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': False,
        'baserow_row_id': 104,
    },
    'DE411': {
        'delentreprenad': 'DE411 - Vakant',
        'namn': 'Vakant',
        'nummer': '411',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': False,
        'baserow_row_id': 105,
    },
    'DE412': {
        'delentreprenad': 'DE412 - Vakant',
        'namn': 'Vakant',
        'nummer': '412',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': False,
        'baserow_row_id': 106,
    },
    'DE413': {
        'delentreprenad': 'DE413 - Vakant',
        'namn': 'Vakant',
        'nummer': '413',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': False,
        'baserow_row_id': 107,
    },
    'DE414': {
        'delentreprenad': 'DE414 - Vakant',
        'namn': 'Vakant',
        'nummer': '414',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': False,
        'baserow_row_id': 108,
    },
    'DE415': {
        'delentreprenad': 'DE415 - Vakant',
        'namn': 'Vakant',
        'nummer': '415',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': False,
        'baserow_row_id': 109,
    },
    'DE416': {
        'delentreprenad': 'DE416 - Vakant',
        'namn': 'Vakant',
        'nummer': '416',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': False,
        'baserow_row_id': 110,
    },
    'DE417': {
        'delentreprenad': 'DE417 - Vakant',
        'namn': 'Vakant',
        'nummer': '417',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': False,
        'baserow_row_id': 111,
    },
    'DE418': {
        'delentreprenad': 'DE418 - Vakant',
        'namn': 'Vakant',
        'nummer': '418',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': False,
        'baserow_row_id': 112,
    },
    'DE419': {
        'delentreprenad': 'DE419 - Vakant',
        'namn': 'Vakant',
        'nummer': '419',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': False,
        'baserow_row_id': 113,
    },
    'DE420': {
        'delentreprenad': 'DE420 - Vakant',
        'namn': 'Vakant',
        'nummer': '420',
        'huvudgrupp': '4. YTSKIKTSENTREPRENADER',
        'huvudgrupp_id': 3844,
        'grupp': '4',
        'modelleras_3d': False,
        'baserow_row_id': 114,
    },
    'DE500': {
        'delentreprenad': 'DE500 -',
        'namn': '',
        'nummer': '500',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': False,
        'baserow_row_id': 115,
    },
    'DE501': {
        'delentreprenad': 'DE501 - Pentry & Dörrar',
        'namn': 'Pentry & Dörrar',
        'nummer': '501',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 116,
    },
    'DE502': {
        'delentreprenad': 'DE502 - Lister och foder',
        'namn': 'Lister och foder',
        'nummer': '502',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 117,
    },
    'DE503': {
        'delentreprenad': 'DE503 - Lås och beslag (dörrautomatik)',
        'namn': 'Lås och beslag (dörrautomatik)',
        'nummer': '503',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 118,
    },
    'DE504': {
        'delentreprenad': 'DE504 - Skyltning/foliering',
        'namn': 'Skyltning/foliering',
        'nummer': '504',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 119,
    },
    'DE505': {
        'delentreprenad': 'DE505 - Fasadskylting',
        'namn': 'Fasadskylting',
        'nummer': '505',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 120,
    },
    'DE506': {
        'delentreprenad': 'DE506 - Fasta möbler',
        'namn': 'Fasta möbler',
        'nummer': '506',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 121,
    },
    'DE507': {
        'delentreprenad': 'DE507 - Lösa möbler',
        'namn': 'Lösa möbler',
        'nummer': '507',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 122,
    },
    'DE508': {
        'delentreprenad': 'DE508 - Kyl- & frysrum',
        'namn': 'Kyl- & frysrum',
        'nummer': '508',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 123,
    },
    'DE509': {
        'delentreprenad': 'DE509 - Storköksutrustning',
        'namn': 'Storköksutrustning',
        'nummer': '509',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 124,
    },
    'DE510': {
        'delentreprenad': 'DE510 - Labbutrustning',
        'namn': 'Labbutrustning',
        'nummer': '510',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 125,
    },
    'DE511': {
        'delentreprenad': 'DE511 - Renrum',
        'namn': 'Renrum',
        'nummer': '511',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 126,
    },
    'DE512': {
        'delentreprenad': 'DE512 - Konstverk',
        'namn': 'Konstverk',
        'nummer': '512',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 127,
    },
    'DE513': {
        'delentreprenad': 'DE513 - Historiska rum',
        'namn': 'Historiska rum',
        'nummer': '513',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 128,
    },
    'DE514': {
        'delentreprenad': 'DE514 - Skyddsrum',
        'namn': 'Skyddsrum',
        'nummer': '514',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 129,
    },
    'DE515': {
        'delentreprenad': 'DE515 - Taksäkerhet',
        'namn': 'Taksäkerhet',
        'nummer': '515',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': True,
        'baserow_row_id': 130,
    },
    'DE516': {
        'delentreprenad': 'DE516 - Vakant',
        'namn': 'Vakant',
        'nummer': '516',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': False,
        'baserow_row_id': 131,
    },
    'DE517': {
        'delentreprenad': 'DE517 - Vakant',
        'namn': 'Vakant',
        'nummer': '517',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': False,
        'baserow_row_id': 132,
    },
    'DE518': {
        'delentreprenad': 'DE518 - Vakant',
        'namn': 'Vakant',
        'nummer': '518',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': False,
        'baserow_row_id': 133,
    },
    'DE519': {
        'delentreprenad': 'DE519 - Vakant',
        'namn': 'Vakant',
        'nummer': '519',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': False,
        'baserow_row_id': 134,
    },
    'DE520': {
        'delentreprenad': 'DE520 - Vakant',
        'namn': 'Vakant',
        'nummer': '520',
        'huvudgrupp': '5. INREDNING OCH UTRUSTNING',
        'huvudgrupp_id': 3845,
        'grupp': '5',
        'modelleras_3d': False,
        'baserow_row_id': 135,
    },
    'DE600': {
        'delentreprenad': 'DE600 -',
        'namn': '',
        'nummer': '600',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 136,
    },
    'DE601': {
        'delentreprenad': 'DE601 - Utsättning & Inmätning',
        'namn': 'Utsättning & Inmätning',
        'nummer': '601',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 137,
    },
    'DE602': {
        'delentreprenad': 'DE602 - Kittentreprenaden/Byggservice',
        'namn': 'Kittentreprenaden/Byggservice',
        'nummer': '602',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 138,
    },
    'DE603': {
        'delentreprenad': 'DE603 - Logistik',
        'namn': 'Logistik',
        'nummer': '603',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 139,
    },
    'DE604': {
        'delentreprenad': 'DE604 - Avfallshantering',
        'namn': 'Avfallshantering',
        'nummer': '604',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': True,
        'baserow_row_id': 140,
    },
    'DE605': {
        'delentreprenad': 'DE605 - Tillfälliga fabriken',
        'namn': 'Tillfälliga fabriken',
        'nummer': '605',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 141,
    },
    'DE606': {
        'delentreprenad': 'DE606 - Ställning och väderskydd',
        'namn': 'Ställning och väderskydd',
        'nummer': '606',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': True,
        'baserow_row_id': 142,
    },
    'DE607': {
        'delentreprenad': 'DE607 - Stämp',
        'namn': 'Stämp',
        'nummer': '607',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': True,
        'baserow_row_id': 143,
    },
    'DE608': {
        'delentreprenad': 'DE608 - TA-plan/APD',
        'namn': 'TA-plan/APD',
        'nummer': '608',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': True,
        'baserow_row_id': 144,
    },
    'DE609': {
        'delentreprenad': 'DE609 - Kran',
        'namn': 'Kran',
        'nummer': '609',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': True,
        'baserow_row_id': 145,
    },
    'DE610': {
        'delentreprenad': 'DE610 - Lyft/Transport',
        'namn': 'Lyft/Transport',
        'nummer': '610',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': True,
        'baserow_row_id': 146,
    },
    'DE611': {
        'delentreprenad': 'DE611 - Byggventilation',
        'namn': 'Byggventilation',
        'nummer': '611',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 147,
    },
    'DE612': {
        'delentreprenad': 'DE612 - Byggvärme',
        'namn': 'Byggvärme',
        'nummer': '612',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 148,
    },
    'DE613': {
        'delentreprenad': 'DE613 - Byggvatten',
        'namn': 'Byggvatten',
        'nummer': '613',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 149,
    },
    'DE614': {
        'delentreprenad': 'DE614 - Byggel',
        'namn': 'Byggel',
        'nummer': '614',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 150,
    },
    'DE615': {
        'delentreprenad': 'DE615 - Bygghiss',
        'namn': 'Bygghiss',
        'nummer': '615',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 151,
    },
    'DE616': {
        'delentreprenad': 'DE616 - Bodar',
        'namn': 'Bodar',
        'nummer': '616',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': True,
        'baserow_row_id': 152,
    },
    'DE617': {
        'delentreprenad': 'DE617 - Snöröjning',
        'namn': 'Snöröjning',
        'nummer': '617',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 153,
    },
    'DE618': {
        'delentreprenad': 'DE618 - Skyddsutrustning',
        'namn': 'Skyddsutrustning',
        'nummer': '618',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': True,
        'baserow_row_id': 154,
    },
    'DE619': {
        'delentreprenad': 'DE619 - Vepor, Skyltar och foliering',
        'namn': 'Vepor, Skyltar och foliering',
        'nummer': '619',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': True,
        'baserow_row_id': 155,
    },
    'DE620': {
        'delentreprenad': 'DE620 - Hyror',
        'namn': 'Hyror',
        'nummer': '620',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': True,
        'baserow_row_id': 156,
    },
    'DE621': {
        'delentreprenad': 'DE621 - Byggstäd',
        'namn': 'Byggstäd',
        'nummer': '621',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 157,
    },
    'DE622': {
        'delentreprenad': 'DE622 - Slutstäd',
        'namn': 'Slutstäd',
        'nummer': '622',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 158,
    },
    'DE623': {
        'delentreprenad': 'DE623 - ByggWiFi',
        'namn': 'ByggWiFi',
        'nummer': '623',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 159,
    },
    'DE624': {
        'delentreprenad': 'DE624 - Vakant',
        'namn': 'Vakant',
        'nummer': '624',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 160,
    },
    'DE625': {
        'delentreprenad': 'DE625 - Vakant',
        'namn': 'Vakant',
        'nummer': '625',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 161,
    },
    'DE626': {
        'delentreprenad': 'DE626 - Vakant',
        'namn': 'Vakant',
        'nummer': '626',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 162,
    },
    'DE627': {
        'delentreprenad': 'DE627 - Vakant',
        'namn': 'Vakant',
        'nummer': '627',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 163,
    },
    'DE628': {
        'delentreprenad': 'DE628 - Vakant',
        'namn': 'Vakant',
        'nummer': '628',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 164,
    },
    'DE629': {
        'delentreprenad': 'DE629 - Vakant',
        'namn': 'Vakant',
        'nummer': '629',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 165,
    },
    'DE630': {
        'delentreprenad': 'DE630 - Vakant',
        'namn': 'Vakant',
        'nummer': '630',
        'huvudgrupp': '6. APO / TILLFÄLLIGA ANNORDNINGAR',
        'huvudgrupp_id': 3846,
        'grupp': '6',
        'modelleras_3d': False,
        'baserow_row_id': 166,
    },
}

VALID_DE_CODES = frozenset(DELENTREPRENADER.keys())


def get_delentreprenad(code: str) -> dict[str, Any] | None:
    """Return Baserow metadata for a DE code, or None."""
    if not code:
        return None
    return DELENTREPRENADER.get(code.strip())


def validate_contract_id(code: str) -> bool:
    """Return True when *code* is a known delentreprenad ID from Baserow."""
    if not code or not isinstance(code, str):
        return False
    return code.strip() in DELENTREPRENADER


_KG = 'BIP."BSABe/Kostengruppe"'


def _rule(selector: str, contract_id: str, *, require_not_duplicate: bool = True) -> dict:
    return {
        "selector": selector,
        "contract_id": contract_id,
        "require_not_duplicate": require_not_duplicate,
    }


# First match wins (see AssignContractIDFromRules.patch).
CONTRACT_ID_RULES: list[dict] = [
    # IFC class defaults
    _rule("IfcCurtainWall", "DE114"),
    _rule("IfcWindow", "DE117"),
    _rule("IfcDoor", "DE315"),
    _rule("IfcRailing", "DE515"),
    # IfcWall — Kostengruppe / TypeID
    _rule(f'IfcWall, {_KG}*=337', "DE114"),
    _rule("IfcWall, BIP.TypeID*=OW", "DE119"),
    _rule(f'IfcWall, {_KG}*=332', "DE119"),
    _rule(f'IfcWall, {_KG}*=341', "DE113"),
    _rule(f'IfcWall, {_KG}*=342', "DE306"),
    _rule(f'IfcWall, {_KG}*=346', "DE307"),
    _rule(f'IfcWall, {_KG}*=331', "DE119"),
    _rule(f'IfcColumn, {_KG}*=343', "DE112"),
    _rule(f'IfcBeam, {_KG}*=351', "DE112"),
    # IfcCovering
    _rule(f'IfcCovering, {_KG}*=354', "DE408"),
    _rule(f'IfcCovering, {_KG}*=353', "DE403"),
    _rule(f'IfcCovering, {_KG}*=345', "DE407"),
    # IfcStair
    _rule(f'IfcStair, {_KG}*=351', "DE126"),
    _rule(f'IfcStair, {_KG}*=361', "DE125"),
    # Roof — beams and coverings (DIN 361 / 363 / 364)
    _rule(f'IfcBeam, {_KG}*=361', "DE123"),
    _rule(f'IfcBeam, {_KG}*=363', "DE123"),
    _rule(f'IfcBeam, {_KG}*=364', "DE123"),
    _rule(f'IfcCovering, {_KG}*=361', "DE123"),
    _rule(f'IfcCovering, {_KG}*=363', "DE123"),
    _rule(f'IfcCovering, {_KG}*=364', "DE123"),
    # Kostengruppe-only (any element class)
    _rule(f'IfcElement, {_KG}*=335', "DE122"),
    _rule(f'IfcElement, {_KG}*=336', "DE122"),
    _rule(f'IfcElement, {_KG}*=322', "DE108"),
    _rule(f'IfcSlab, {_KG}*=322', "DE109"),
    _rule(f'IfcBeam, {_KG}*=322', "DE109"),
    _rule(f'IfcElement, {_KG}*=440', "DE213"),
    # Slab catch-all
    _rule("IfcSlab", "DE109"),
]

