services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - ifcconvert
      - ifcclash
      - ifccsv
      - ifctester
      - ifcdiff
      - ifc5d
    environment:
      - IFCCONVERT_URL=http://ifcconvert
      - IFCCLASH_URL=http://ifcclash
      - IFCCSV_URL=http://ifccsv
      - IFCTESTER_URL=http://ifctester
      - IFCDIFF_URL=http://ifcdiff
      - IFC5D_URL=http://ifc5d
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
      - IFC_PIPELINE_API_KEY=${IFC_PIPELINE_API_KEY}
      - IFC_PIPELINE_ALLOWED_IP_RANGES=${IFC_PIPELINE_ALLOWED_IP_RANGES}
    volumes:
      - ./shared/uploads:/app/uploads
      - ./shared/output:/app/output
      - ./shared/examples:/app/examples
    restart: unless-stopped

  ifc5d:
    build:
      context: .
      dockerfile: ifc5d/Dockerfile
    volumes:
      - ./shared/uploads:/app/uploads
      - ./shared/output:/app/output
      - ./shared/examples:/app/examples
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: unless-stopped

  ifcconvert:
    build:
      context: .
      dockerfile: ifcconvert/Dockerfile
    volumes:
      - ./shared/uploads:/app/uploads
      - ./shared/output:/app/output
      - ./shared/examples:/app/examples
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: unless-stopped

  ifcclash:
    build:
      context: .
      dockerfile: ifcclash/Dockerfile
    volumes:
      - ./shared/uploads:/app/uploads
      - ./shared/output:/app/output
      - ./shared/examples:/app/examples
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: unless-stopped

  ifccsv:
    build:
      context: .
      dockerfile: ifccsv/Dockerfile
    volumes:
      - ./shared/uploads:/app/uploads
      - ./shared/output:/app/output
      - ./shared/examples:/app/examples
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: unless-stopped

  ifctester:
    build:
      context: .
      dockerfile: ifctester/Dockerfile
    volumes:
      - ./shared/uploads:/app/uploads
      - ./shared/output:/app/output
      - ./shared/examples:/app/examples
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: unless-stopped

  ifcdiff:
    build:
      context: .
      dockerfile: ifcdiff/Dockerfile
    volumes:
      - ./shared/uploads:/app/uploads
      - ./shared/output:/app/output
      - ./shared/examples:/app/examples
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n
    user: root
    ports:
      - "5678:5678"
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./shared/uploads:/uploads
      - ./shared/output:/output
      - ./shared/examples:/examples
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - IFC_PIPELINE_URL=http://api-gateway
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - N8N_SECURE_COOKIE=false
      - TZ=Europe/Stockholm
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=${N8N_COMMUNITY_PACKAGES_ENABLED}
    depends_on:
      - api-gateway
    restart: unless-stopped

  ifc2json:
    build:
      context: .
      dockerfile: ifc2json/Dockerfile
    volumes:
      - ./shared/uploads:/app/uploads
      - ./shared/output:/app/output
      - ./shared/examples:/app/examples
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: unless-stopped

volumes:
  shared: