version: '3'
services:
  n8n:
      stdin_open: true
      tty: true
      container_name: n8n
      ports:
          - 5678:5678
      volumes:
          - ~/.n8n:/home/node/.n8n
      image: docker.n8n.io/n8nio/n8n
      command: n8n start --tunnel

  ifc-pipeline:
    build:
      context: .
      dockerfile: images/ifc-pipeline/Dockerfile
    ports:
      - "8001:8000"
