services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - ifcconvert
      - ifcclash
      - ifccsv
      - ifctester
      - ifcdiff_worker
      - ifc5d
      - redis
    environment:
      - IFCCONVERT_URL=http://ifcconvert
      - IFCCLASH_URL=http://ifcclash
      - IFCCSV_URL=http://ifccsv
      - IFCTESTER_URL=http://ifctester
      - IFCDIFF_URL=http://ifcdiff_worker
      - IFC5D_URL=http://ifc5d
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
      - REDIS_HOST=redis
      - IFC_PIPELINE_API_KEY=${IFC_PIPELINE_API_KEY}
      - IFC_PIPELINE_ALLOWED_IP_RANGES=${IFC_PIPELINE_ALLOWED_IP_RANGES}
    volumes:
      - ./shared/uploads:/uploads
      - ./shared/output:/output
      - ./shared/examples:/examples
    restart: unless-stopped

  ifc5d:
    build:
      context: .
      dockerfile: ifc5d/Dockerfile
    volumes:
      - ./shared/uploads:/uploads
      - ./shared/output:/output
      - ./shared/examples:/examples
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: unless-stopped

  ifcconvert:
    build:
      context: .
      dockerfile: ifcconvert/Dockerfile
    volumes:
      - ./shared/uploads:/uploads
      - ./shared/output:/output
      - ./shared/examples:/examples
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: unless-stopped

  ifcclash:
    build:
      context: .
      dockerfile: ifcclash/Dockerfile
    volumes:
      - ./shared/uploads:/uploads
      - ./shared/output:/output
      - ./shared/examples:/examples
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: unless-stopped

  ifccsv:
    build:
      context: .
      dockerfile: ifccsv/Dockerfile
    volumes:
      - ./shared/uploads:/uploads
      - ./shared/output:/output
      - ./shared/examples:/examples
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: unless-stopped

  ifctester:
    build:
      context: .
      dockerfile: ifctester/Dockerfile
    volumes:
      - ./shared/uploads:/uploads
      - ./shared/output:/output
      - ./shared/examples:/examples
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: unless-stopped

  ifcdiff_worker:
    build:
      context: .
      dockerfile: ifcdiff_worker/Dockerfile
    command: bash -c "cd /app && PYTHONPATH=/app rq worker -u redis://redis:6379 --worker-ttl 3600 --with-scheduler ifcdiff-tasks"
    volumes:
      - ./shared/uploads:/uploads
      - ./shared/output:/output
      - ./shared/examples:/examples
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
      - REDIS_HOST=redis
      - PYTHONPATH=/app
    depends_on:
      - redis
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./shared/uploads:/uploads
      - ./shared/output:/output
      - ./shared/examples:/examples
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - IFC_PIPELINE_URL=http://api-gateway
      - WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Europe/Stockholm
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=${N8N_COMMUNITY_PACKAGES_ENABLED}
      - N8N_RUNNERS_ENABLED=true
    depends_on:
      - api-gateway
      - redis
    restart: unless-stopped

  ifc2json:
    build:
      context: .
      dockerfile: ifc2json/Dockerfile
    volumes:
      - ./shared/uploads:/uploads
      - ./shared/output:/output
      - ./shared/examples:/examples
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: unless-stopped

  redis:
    image: "redis:7-alpine"
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - redis-data:/data

  rq-dashboard:
    image: eoranged/rq-dashboard
    ports:
      - "9181:9181"
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  shared:
  redis-data: