version: '3'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./ifcpipeline/models:/models
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - IFC_PIPELINE_URL=http://ifcpipeline
    depends_on:
      - ifcpipeline

  ifcpipeline:
    build:
      context: ./ifcpipeline
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./ifcpipeline/models:/app/models
      - ./ifcpipeline/output:/app/output
      - ./ifcpipeline/ids:/app/ids
