#!/usr/bin/env bash
# Sync ifcpipeline to a worker host and start remote workers over SSH.
# Run on the primary host from repo root (requires .env and passwordless SSH).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

REMOTE_SSH="${REMOTE_SSH:-deploy@worker-host}"
REMOTE_REPO="${REMOTE_REPO:-/home/deploy/apps/ifcpipeline}"
PIPELINE_HOST="${PIPELINE_HOST:-primary-host}"
ENV_REMOTE_NAME="${ENV_REMOTE_NAME:-.env.remote}"
SSH_OPTS=(-o RemoteCommand=none -o RequestTTY=no)
RSYNC_SSH="ssh ${SSH_OPTS[*]}"

REMOTE_ENV_KEYS=(
  POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB POSTGRES_PORT
  USE_OBJECT_STORAGE S3_ACCESS_KEY S3_SECRET_KEY
  S3_BUCKET S3_REGION S3_CHECKSUM_MODE LOG_LEVEL
  IFCPATCH_DEBUG IFCPATCH_CORE_LIMIT IFCPATCH_REMOTE_REPLICAS
  IFCTESTER_REMOTE_REPLICAS IFCCLASH_REMOTE_REPLICAS IFCDIFF_REMOTE_REPLICAS
  IFCCLASH_GEOMETRY_LIBRARY IFCCLASH_ITERATOR_THREADS IFCCLASH_ISOLATE
  IFCCLASH_BVH_CACHE IFCCLASH_BVH_CACHE_DIR IFCCLASH_BVH_CACHE_MAX_MB
  IFCCLASH_BVH_CACHE_MINIO_PREFIX
  IFCCLASH_VALIDATE_CACHE IFCCLASH_VALIDATE_CACHE_TTL_S
  IFCCLASH_VALIDATE_CACHE_PREFIX
)

if [[ ! -f .env ]]; then
  echo "error: missing .env in $ROOT (required on primary host)" >&2
  exit 1
fi

if [[ "$REMOTE_SSH" == *"worker-host"* ]] && [[ -z "${REMOTE_SSH_OVERRIDE:-}" ]]; then
  echo "warn: REMOTE_SSH is still the placeholder deploy@worker-host — set REMOTE_SSH to your worker SSH target" >&2
fi

write_env_remote() {
  local tmp
  tmp="$(mktemp)"
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a

  local reach="${PIPELINE_LAN_IP:-$PIPELINE_HOST}"
  {
    echo "# Generated by deploy-remote-workers-from-primary.sh on $(date -Iseconds)"
    echo "PIPELINE_HOST=${PIPELINE_HOST}"
    echo "PIPELINE_LAN_IP=${reach}"
    echo "REDIS_URL=redis://${reach}:6379/0"
    echo "POSTGRES_HOST=${reach}"
    echo "S3_ENDPOINT_URL=http://${reach}:8333"
  } >"$tmp"

  for key in "${REMOTE_ENV_KEYS[@]}"; do
    if [[ -n "${!key:-}" ]]; then
      printf '%s=%s\n' "$key" "${!key}" >>"$tmp"
    fi
  done

  echo "$tmp"
}

echo "==> Ensure ${REMOTE_REPO} exists on worker"
ssh "${SSH_OPTS[@]}" "$REMOTE_SSH" "mkdir -p '${REMOTE_REPO}'"

echo "==> Rsync to ${REMOTE_SSH}:${REMOTE_REPO} (worker-minimal; images from primary)"
RSYNC_EXCLUDES=(
  --exclude '.git'
  --exclude '.env'
  --exclude '.env.remote'
  --exclude 'n8n-data/'
  --exclude 'n8n-workflows/'
  --exclude 'hunt-evidence/'
  --exclude 'parity-reports/'
  --exclude 'shared/uploads/'
  --exclude 'shared/output/'
  --exclude 'shared/examples/'
  --exclude 'ifc-viewer/'
  --exclude 'api-gateway/'
  --exclude 'revit-worker/'
  --exclude 'ifc-classifier-service/'
  --exclude 'ifc-classifier/'
  --exclude 'rq-dashboard-custom/'
  --exclude 'postgres/'
  --exclude 'seaweedfs/'
  --exclude 'parity-monitor/'
  --exclude 'daily-smoke/'
  --exclude 'example n8n workflows/'
  --exclude 'ifcconvert-worker/'
  --exclude 'ifccsv-worker/'
  --exclude 'ifcdiff-worker/'
  --exclude 'ifc5d-worker/'
  --exclude 'ifc2json-worker/'
  --exclude 'guid-index-worker/'
  --exclude 'cleanup-service/'
  --exclude 'tests/'
  --exclude 'patches/'
  --exclude '*.md'
)
rsync -av --delete \
  "${RSYNC_EXCLUDES[@]}" \
  -e "$RSYNC_SSH" \
  "$ROOT/" "${REMOTE_SSH}:${REMOTE_REPO}/"

echo "==> Upload ${ENV_REMOTE_NAME}"
REMOTE_ENV_TMP="$(write_env_remote)"
scp -q "${SSH_OPTS[@]}" "$REMOTE_ENV_TMP" "${REMOTE_SSH}:${REMOTE_REPO}/${ENV_REMOTE_NAME}"
rm -f "$REMOTE_ENV_TMP"

echo "==> Push pre-built images from primary (avoids building on worker disk)"
"$ROOT/scripts/push-worker-images-to-remote.sh"

echo "==> Remote start (SKIP_BUILD=1 — images loaded from primary)"
ssh "${SSH_OPTS[@]}" "$REMOTE_SSH" "cd '${REMOTE_REPO}' && chmod +x scripts/*.sh && SKIP_BUILD=1 ./scripts/start-remote-workers.sh"

echo "==> Done. Check rq-dashboard on primary (port 9181) for new workers."
